sudo: required
language: python
services:
- docker
python:
- '3.6'
before_script:
- docker-compose build
script:
- docker-compose run --rm web bash -c "flake8 . && python wait_for_postgres.py &&
  ./manage.py test"
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then docker login --username=_ --password="$HEROKU_AUTH_TOKEN"
    registry.heroku.com; docker tag web registry.heroku.com/sweethandy-prod/web; docker
    push registry.heroku.com/sweethandy-prod/web; fi
  - if [ "$TRAVIS_BRANCH" == "qa" ]; then docker login --username=_ --password="$HEROKU_AUTH_TOKEN"
    registry.heroku.com; docker tag web registry.heroku.com/sweethandy-qa/web; docker
    push registry.heroku.com/sweethandy-qa/web; fi  
notifications:
  email: false
cache:
  pip: true
env:
  global:
    secure: adgwVEEfyVzTEtHOPDeiHfh03LCZHU1BNJ96ihorXsdih3Ksj/4hvK2wcmKT4xJpsatJzEfW/nwhpugigMMgzeWlkwSal3i8rSY/TCUTFUjcQA4fUv9uK5y+SuavxicvieYj6MrPSXotnJT8yaD9kYK/hgIo1NhyH4OWjJyCZ+hqi9+hgYfhO7Uw89l7T9lxECvzktVpd9sPMjI0fTcSBtnu+CCVyep4BW84VzKQA4yoT0fo48C2+l1N0SKLUBTKo1KCr9NU5DxFfRTggjRn/AZdQZebN1yU/9vXwiQmmpmL5SbkUSUjWQU8zSqmrIUB4IhSjrThIXI+dYJniUXMafdRFO4tzc4ZzCLrmoie6mbseXRbNcoaWqcXqH1sRRCTH2lvNr46Mi7kiYNusAupvL9KYbkky7WnpswYc1j3/8GcgHr0kTb7JbUeLgX5eGXKXOcs1SAzSILOVHozblcSWYmpITH1L4yo/RsEQFsByw5GgjwwBCEAwnSmiYYmRThzydfWOmyqSQB7IuFPFliRx/YmAWmm2gJt55TzaKWWxD8P9RjjhoHGeCXjaXYNlNI3dE+ivxyHyofMTzwb7Z8ykZ3PyfhzjJyypWgM+NiW1lEZSOBK1ez9ZTaqiWrRNgI+w6AOKxYxrNZ9YxLUUogQ/OpnOQjDFdIhOYN5WNRm6pc=
